version: '3.8'

services:
  notifymed_api:
    build:
      context: .
      dockerfile: NotifyMed.API/Dockerfile
    container_name: notifymed_api
    ports:
      - "5005:80"  # 🔹 Porta exposta corretamente
    networks:
      - monitoring_network  # 🔹 Compartilha a mesma redes
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=seu_email@gmail.com
      - EMAIL_PASSWORD=sua_senha
    # depends_on:
    #   - rabbitmq

networks:
  monitoring_network:
    external: true  # 🔹 Garante que todas as APIs se comuniquem
